spring.application.name=loganalyzer
# H2 Database (in-memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#kafka
spring.kafka.bootstrap-servers=kafka:9092

#openAPI
openai.api.key=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